# Generated by Django 2.2.4 on 2024-07-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20240722_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='course_app.Description'),
            preserve_default=False,
        ),
    ]
